// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"john doe",
    "email":"john@gmail.com",
    "password":"123456",
    "confPassword":"123456",
    "role":"user"

}

###
//get all users
GET http://localhost:5000/users

###
//get single user
GET http://localhost:5000/users/37ca1953-2a98-4623-8a51-99729ca432da

###
//update user
PATCH http://localhost:5000/users/5506e5e3-b14f-4852-b1d3-d91082814a48
Content-Type: application/json

{
    "name":"john updated",
    "email":"john@gmail.com",
    "password":"",
    "confPassword":"",
    "role":"user"

}
###
//delete user
DELETE http://localhost:5000/users/9cfa3afb-cbf8-43be-bf98-4d7d0d6c816f

###
//Login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"elias3@gmail.com",
    "password":"123456"
  
}

###
GET http://localhost:5000/me

###
DELETE http://localhost:5000/logout


###
//Login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"john@gmail.com",
    "password":"123456"
  
}
###
###
//get all products
GET http://localhost:5000/products


###
//get single product
GET http://localhost:5000/products/d21f1114-dc64-4eeb-a600-30a6b912653b

###
// post data product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name":"product 90",
    "price":8953
    
}

###update data product
// post data product
PATCH  http://localhost:5000/products/91960ad8-3868-448f-b4e2-acf5024b10b3
Content-Type: application/json

{
    "name":"product 6 updated",
    "price":8953
    
}

###Delete data product
DELETE http://localhost:5000/products/d21f1114-dc64-4eeb-a600-30a6b912653b


###Test url ngrock login
POST  https://ee00-37-6-251-229.ngrok-free.app/login
Content-Type: application/json

{
    "email":"john@gmail.com",
    "password":"123456"
  
}

###Test get users
GET https://ee00-37-6-251-229.ngrok-free.app/products

####Get building
GET http://localhost:5000/buildings


### Create a building
POST http://localhost:5000/buildings
Content-Type: application/json

{
    "name":"new peiroxi9",
    "lat":38.06472785053161,
    "lon":23.652481021764597

}

###
//get single product
GET http://localhost:5000/buildings/db6bff60-2142-4e2f-96da-207c83c65056
###
//update single product
PATCH  http://localhost:5000/buildings/db6bff60-2142-4e2f-96da-207c83c65056
Content-Type: application/json

{
    "name":"xomaterupdate25",
    "lat":34.43334,
    "lon":66.53334

}


###Delete building data base on uuid
DELETE http://localhost:5000/buildings/25173aa3-4216-4d54-9251-acbe2f44ae5c



####Get Metrics
GET http://localhost:5000/metrics


### Create a metrics
POST http://localhost:5000/metrics
Content-Type: application/json

{
    "name":"TSP"
   

}

###
//get single metrics
GET http://localhost:5000/metrics/d1b10d14-7226-4362-b87a-bd2e0b08de87
###
//update single metrics
PATCH http://localhost:5000/metrics/d1b10d14-7226-4362-b87a-bd2e0b08de87
Content-Type: application/json

{
    "name":"vffvdfggdgdf"
    
}


###Delete metrics data base on uuid
DELETE http://localhost:5000/metrics/d1b10d14-7226-4362-b87a-bd2e0b08de87


###GET BUILDING metrics
GET http://localhost:5000/buildingmetrics


###
//Login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"elias3@gmail.com",
    "password":"123456"
  
}
